<?php

namespace Database\Seeders\init;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::insert("INSERT INTO `product_products` (`id`, `product_partner_id`, `product_type_id`, `short`, `name`) VALUES
            (1, 4,  13, 'ALL_HYBRID',   'Allianz - MOJE AUTO - PZP + KASKO (HYBRID)'),
            (2, 4,  11, 'ALL_PZP',  'Allianz - MOJE AUTO - PZP poi. motor. vozidiel'),
            (5, 13, 11, 'ČSOB_PZP', 'ČSOB - PZP'),
            (6, 4,  8,  'ALL_KAS_FL',   'Allianz - flotilové poistenie KASKO'),
            (8, 4,  13, 'ALL_HYB_FL',   'Allianz - flotilové poistenie HYBRID'),
            (9, 25, 11, 'GEN_PZP',  'Generali - PZP'),
            (17,    13, 8,  'ČSOB_HAV', 'ČSOB - havaríjne poi. MV - KASKO'),
            (22,    25, 8,  'GEN_KASKO',    'Generali - KASKO'),
            (81,    4,  11, 'ALL_PZP_FL',   'Allianz - flotilové poistenie PZP'),
            (208,   25, 11, 'GEN_PZP',  'Genertel - PZP'),
            (210,   25, 8,  'GEN_KASKO',    'Genertel - KASKO');");

//        DB::insert("INSERT INTO `product_products` (`id`, `product_partner_id`, `product_type_id`, `short`, `name`) VALUES
////            (1, 4,  13, 'ALL_HYBRID',   'Allianz - MOJE AUTO - PZP + KASKO (HYBRID)'),
////            (2, 4,  11, 'ALL_PZP',  'Allianz - MOJE AUTO - PZP poi. motor. vozidiel'),
//            (3, 6,  11, 'UNQ_PZP',  'UNIQA - PZP'),
//            (4, 29, 11, 'KOOP_PZP', 'Kooperativa - PZP'),
////            (5, 13, 11, 'ČSOB_PZP', 'ČSOB - PZP'),
////            (6, 4,  8,  'ALL_KAS_FL',   'Allianz - flotilové poistenie KASKO'),
//            (7, 28, 11, 'KOM_PZP',  'Komunálna - Poistenie zodpovednosti za škodu spôsobenú prevádzkou MV'),
////            (8, 4,  13, 'ALL_HYB_FL',   'Allianz - flotilové poistenie HYBRID'),
////            (9, 25, 11, 'GEN_PZP',  'Generali - PZP'),
//            (10,    3,  11, 'WUS_PZP',  'Wustenrot - PZP'),
//            (11,    10, 11, 'UNI_PZP',  'UNION - Povinné zmluvné poistenie'),
//            (12,    6,  13, 'UNQ_HYBRID',   'UNIQA - Auto & Pohoda - HYBRID'),
//            (13,    3,  8,  'WUS_HAV',  'Wustenrot -  KASKO'),
//            (14,    10, 8,  'UNI_HAV',  'UNION - Havarijné poistenie FO/PO'),
//            (15,    6,  8,  'UNQ_KASKO',    'UNIQA - Auto & Pohoda - KASKO'),
//            (16,    2,  16, '365_HYPO', '365. bank - Hypotéka'),
////            (17,    13, 8,  'ČSOB_HAV', 'ČSOB - havaríjne poi. MV - KASKO'),
//            (18,    28, 8,  'KOM_HAV',  'Komunálna - Havaríjne poistenie'),
//            (19,    12, 16, 'ČSOB_HYPO',    'ČSOB banka - Hypotéka'),
//            (20,    30, 16, 'mBANK_HYPO',   'mBANK - Hypotéka'),
//            (21,    29, 8,  'KOOP_KASKO',   'Kooperativa - havarijne poistenie'),
////            (22,    25, 8,  'GEN_KASKO',    'Generali - KASKO'),
//            (23,    22, 16, 'SLSP_HYPO',    'SLSP - Hypotéka'),
//            (24,    14, 16, 'UCB_HYPO', 'UCB - HYPOÚVER'),
//            (25,    18, 16, 'TB_HYPO',  'TATRA BANKA - Hypotéka'),
//            (26,    15, 18, 'ČSOB_LEAS_POD',    'ČSOB - Leasing (pre podnikateľov)'),
//            (27,    5,  16, 'VUB_HYPO', 'VÚB BANKA - Hypotéka'),
//            (28,    19, 18, 'TATRA_LEAS',   'Tatra - Leasing'),
//            (29,    14, 17, 'UCB_HYP_R',    'UCB - HYPOÚVER refinančný'),
//            (30,    22, 17, 'SLSP_HYP_R',   'SLSP - Hypotéka refinančná'),
//            (31,    18, 17, 'TB_HYP_REF',   'TATRA BANKA - Hypotéka refinančná'),
//            (32,    30, 17, 'mB_HYPO_R',    'mBANK - Hypotéka refinančná'),
//            (33,    12, 17, 'ČSOB_HYP_R',   'ČSOB banka - Hypotéka refinančná'),
//            (34,    5,  17, 'VUB_HYP_R',    'VÚB BANKA - Hypotéka refinančná'),
//            (35,    2,  17, '365_HYP_R',    '365. bank - Hypotéka refinančná'),
//            (36,    12, 20, 'ČSOB_POU', 'ČSOB Banka- Podnikateľský úver'),
//            (37,    5,  21, 'VUB_SP_dom',   'VÚB  - pôžička na investíciu do domácnosti'),
//            (38,    5,  22, 'VUB_SP_R_D',   'VÚB - ref. pôžička na investíciu do domácnosti'),
//            (39,    14, 20, 'UCB_POU',  'UCB - Investičný úver (pre vlast. bytov a nebyt.priestorov)'),
//            (40,    14, 20, 'UCB_KKU',  'UCB  - Kontokorentný úver (PO)'),
//            (41,    14, 20, 'UCB_SPU',  'UCB - Splátkový úver (SZČO/PO)'),
//            (42,    2,  21, '365_SPU',  '365 banka - Spotrebný úver'),
//            (43,    2,  22, '365_SPU_R',    '365 banka - ref. spotrebný úver'),
//            (44,    22, 21, 'SLPS_SÚ',  'SLSP - Spotrebný úver k úveru na bývanie (KOMBO)'),
//            (45,    22, 21, 'SLSP_SPU_R',   'SLSP - ref. spotrebný úver k úveru na býv.(KOMBO)'),
//            (46,    14, 21, 'UCB_SPU',  'UCB - PRESTO ÚVER (spotrebiteľský úver)'),
//            (47,    30, 21, 'MBK_SPU',  'mBank - Pôžička'),
//            (48,    14, 22, 'UCB_SPU_R',    'UCB - PRESTO ÚVER refin. (spotreb. úver)'),
//            (49,    30, 22, 'MBK_SPU_R',    'mBank - ref. pôžička'),
//            (50,    12, 23, 'ČSOB_POS', 'ČSOB Banka - POS , mPOS (terminál)'),
//            (51,    24, 24, 'PSS_SPSE_JE',  'PSS - Stavebné sporenie (tarif SE a JE)'),
//            (52,    24, 19, 'PSS_spotre',   'PSS - Spotrebiteľský medziúver'),
//            (53,    24, 19, 'PSS_medzi',    'PSS - Medziúver na bývanie'),
//            (54,    4,  12, 'ALL_CP',   'Allianz - cestovné poistenie'),
//            (55,    25, 12, 'GEN_CP_KR',    'Generali - cestovné poistenie krátkodobé'),
//            (56,    25, 12, 'GEN_RCP',  'Generali - cestovné poistenie ročné'),
//            (57,    28, 12, 'KOM_CP',   'Komunálna - Cestovné poistenie'),
//            (58,    29, 12, 'KOOP_CP',  'Kooperativa - Cestovné poistenie'),
//            (59,    10, 12, 'UNI_CPK',  'UNION - cestovné poistenie individuálne UNITRIP'),
//            (60,    10, 12, 'UNI_CPR',  'UNION - cestovné poistenie ročné'),
//            (61,    6,  12, 'UNQ_CP',   'UNIQA - Cestovné poistenie'),
//            (62,    7,  7,  'COL_NEH_VIV',  'Colonnade - Poi. budov a zodp.za škodu VIVA'),
//            (63,    3,  12, 'WUS_CPK',  'Wustenrot - Cestovné poistenie krátkodobé'),
//            (64,    3,  12, 'WUS_CPR',  'Wustenrot - Cestovné poistenie ročné'),
//            (65,    4,  7,  'ALL_DOM',  'Allianz - Môj domov'),
//            (66,    4,  5,  'ALL_MAJ_POD',  'Allianz - Poistenie majetku - podnikatelia'),
//            (67,    7,  10, 'COL_SkÚP', 'Colonnade - skupinové úrazové poistenie'),
//            (68,    7,  4,  'COL_MZS',  'Colonnade - poistenie majetku a zodp. za škodu podnikajúcich FO a PO'),
//            (69,    7,  10, 'COL_SÚP',  'Colonnade - samostatné úrazové poistenie'),
//            (70,    13, 7,  'ČSOB_DBD', 'ČSOB - Poistenie rodinných domov, bytov a domácností'),
//            (71,    25, 7,  'GEN_DOM_EX',   'Generali - DOMino Extra'),
//            (72,    25, 7,  'GEN_DOM_TRI',  'Generali - DOMino Trio'),
//            (73,    25, 4,  'GEN_OBC_ZOZ',  'Generali - Poistenie občianskej zodpovednosti'),
//            (74,    28, 7,  'KOM_ZPD',  'Komunálna - Združené poistenie domácnosti'),
//            (75,    29, 7,  'KOOP_BEZDO',   'Kooperativa - Bezstarostný domov'),
//            (76,    29, 5,  'KOOP_BD',  'Kooperativa - Poistenie bytových domov'),
//            (77,    26, 7,  'PREM_BDD', 'Premium - Poistenie bytov, domov a domácnosti'),
//            (78,    26, 5,  'PREM_BD',  'Premium - Poistenie bytových domov'),
//            (79,    10, 7,  'UNI_DBD',  'UNION - Poistenie rodinných domov a bytov, poistenie domácnosti'),
//            (80,    6,  7,  'UNQ_DBZ',  'UNIQA - Dom & Bezpečie'),
////            (81,    4,  11, 'ALL_PZP_FL',   'Allianz - flotilové poistenie PZP'),
//            (82,    3,  5,  'WUS_PBD',  'Wustenrot - Poistenie bytového domu'),
//            (83,    3,  7,  'WUS_NDZ',  'Wustenrot - Poistenie nehnuteľ., domácnosti a zodp. za škodu'),
//            (84,    4,  6,  'ALL_HOS_ZV',   'Allianz - Poistenie poľnohosp. plodín'),
//            (85,    4,  6,  'ALL_MAJ_PRIE', 'Allianz - Poistenie majetku - priemysel'),
//            (86,    4,  6,  'ALL_MOTO', 'Allianz - Pois. ochrany práv - Podnikateľ - Moto'),
//            (87,    4,  10, 'ALL_SPO',  'Allianz - Skupinové poistenie osôb'),
//            (88,    7,  6,  'COL_DO',   'Colonnade - D&O poistenie'),
//            (89,    7,  10, 'COL_ŮPMV', 'Colonnade - úraz. poi. osôb prepravovaných motor. vozidlom'),
//            (90,    17, 6,  'EH_PODNIK',    'EULER HERMES - Poistenie podnikateľov'),
//            (91,    25, 6,  'GEN_GEB',  'Generali - GEB'),
//            (92,    25, 6,  'GEN_POD',  'Generali - Poistenie podnikateľov'),
//            (93,    25, 6,  'GEN_PRI_RIZ',  'Generali - Poistenie priemyselných rizík'),
//            (94,    25, 6,  'GEN_PLN',  'Generali - Poľnohospodárske poistenie'),
//            (95,    28, 6,  'KOM_FIRMA',    'Komunálna - Produkt č. 442 Moja Firma'),
//            (96,    28, 6,  'KOM_MAJ_PPO',  'Komunálna - Poistenie majetku  a zodpovednosti PPO'),
//            (97,    38, 26, 'NN_DDS',   'NN DDS'),
//            (98,    39, 27, 'NN_DSS',   'NN DSS'),
//            (99,    37, 3,  'NN_PAR',   'NN Partner'),
//            (100,   29, 6,  'KOOP_MAJ_POD', 'Kooperatíva - Poistenie majetku a zodp. PO a SZČO'),
//            (101,   29, 6,  'KOOP_RIZIK',   'Kooperatíva - Prepravné riziká'),
//            (102,   26, 6,  'PREM_SME', 'Premium - Poi. majetku a zodp. za škodu mal. a stred. podnik. - SME'),
//            (103,   26, 6,  'PRE_PRIEMY',   'Premium - Poistenie majetku (priemysel)'),
//            (104,   10, 6,  'UNI_MAJ',  'Union - Poistenie majetku (budov, strojov...)'),
//            (105,   10, 6,  'UNI_SME',  'UNION - Poistenie podnikateľov - SME'),
//            (106,   6,  10, 'UNQ_UCK',  'UNIQA - Úpadok cestovnej kancelárie'),
//            (107,   6,  10, 'UNQ_LES',  'UNIQA - Poistenie zvierat a lesa'),
//            (108,   6,  6,  'UNQ_MAJ_ZOZ',  'UNIQA - Poistenie majetku a zodpovednosť za škodu'),
//            (109,   4,  4,  'ALL_ZOZ',  'Allianz - zodp. za škodu pri výkone povolania'),
//            (110,   7,  12, 'COL_ICP',  'Colonnade - individuálne cestovné poistenie'),
//            (111,   7,  4,  'COL_ZOZSKU',   'Colonnade - zodpovednosť za škodu pri výkone povolania_skupinove'),
//            (112,   25, 4,  'GEN_ZOZ',  'Generali - zodp. za škodu pri výkone povolania'),
//            (113,   29, 4,  'KOOP_ZOZ', 'Kooperativa - Zodp. za škodu pri výkone povolania'),
//            (114,   26, 4,  'PRE_ZOZ',  'Premium - Poistenie profesijnej zodpovednosti'),
//            (115,   26, 4,  'PRE_ZOZVS',    'Premium - Poistenie všeobecnej zodpovednosti'),
//            (116,   10, 4,  'UNI_ZOS',  'UNION - Poi. profesnej zodpovednosti, poi. zodpovednosti za škodu'),
//            (117,   3,  4,  'WUS_ZOZ',  'Wustenrot - Poistenie zodpovednosti za škodu pri výkone povolania'),
//            (118,   10, 9,  'UNI_ZDR_SAF',  'UNION - Zdravotné poistenie cudzincov SAFETY'),
//            (119,   16, 30, 'DOVERA_ZDR',   'Dôvera - zdravotné poistenie'),
//            (120,   4,  10, 'ALL_SUKROM',   'Allianz - Poistenie ochrany práv - súkromie'),
//            (121,   7,  12, 'COL_SkCP', 'Colonnade - skupinové cestovné poistenie'),
//            (122,   10, 9,  'UNI_ZDR_SIM',  'UNION - Zdravotné poistenie cudzincov SIMPLE'),
//            (123,   28, 10, 'KOM_URZ',  'Komunálna - Úrazové poistenie'),
//            (124,   26, 10, 'PRE_SKU',  'Premium - Skupinové úrazové poistenie'),
//            (125,   10, 10, 'UNI_ZDO',  'UNION - Poistenie choroby - Zdravie Optimum'),
//            (126,   10, 10, 'UNI_URZ',  'UNION - Úrazové poistenie ISTOTA'),
//            (127,   6,  10, 'UNQ_OCHRAN',   'UNIQA - Poistenie právnej ochrany'),
//            (128,   6,  10, 'UNQ_URZ_DO2',  'UNIQA - Poistenie úrazu'),
//            (129,   3,  9,  'WUS_ZDRAV',    'Wustenrot - Individuálne zdravotné poistenie'),
//            (130,   3,  10, 'WUS_OCHRAN',   'Wustenrot - Poistenie právnej ochrany'),
//            (131,   3,  10, 'WUS_UPA',  'Wustenrot - Úrazové poistenie AUTO'),
//            (132,   33, 27, 'ALL_DDS',  'Allianz DSS - Starobné dôchodkové sporenie - 2.p.'),
//            (133,   20, 26, 'TB_DDS',   'TB DDS - Účastnícka zmluva'),
//            (134,   20, 26, 'TB_DDSZAME',   'TB DDS - Zamestnávateľská zmluva'),
//            (135,   3,  3,  'WUS_WDOBRO',   'Wüstenrot - W_dobrom život (RP06)'),
//            (136,   13, 3,  'ČSO_VITAL',    'ČSOB - VITAL - rizikový variant'),
//            (137,   25, 3,  'GEN_LAV_RZP',  'Generali - La Vita RŽP'),
//            (138,   28, 3,  'KOM_PIETA',    'Komunálna - Pieta'),
//            (139,   28, 3,  'KOM_PROVIT',   'Komunálna - Provital Partner'),
//            (140,   29, 3,  'KOO_S7',   'Kooperativa - PROFI Komplet S7 Bezstarostný život'),
//            (141,   6,  3,  'UNQ_UNIQAT',   'Uniqa - UNIQAT Risk (R0209)'),
//            (142,   4,  3,  'ALL_STASTN',   'Allianz - Šťastný život'),
//            (143,   7,  7,  'COL_HN_VIV',   'Colonnade - Poi. hnuť. vecí a zodp.za škodu VIVA'),
//            (144,   4,  1,  'ALL_FAR',  'Allianz - Moja Farbička Plus'),
//            (145,   4,  1,  'ALL_STRATE',   'Allianz - Moja Stratégia'),
//            (146,   4,  1,  'ALL_PLUS', 'Allianz - Môj život plus'),
//            (147,   28, 1,  'KOM_JUN',  'Komunálna - Provital Junior'),
//            (148,   6,  1,  'UNQ_INVEST',   'UNIQA - UNIQAT Invest F0209, RP209'),
//            (149,   3,  1,  'WUS_BUDUC',    'Wustenrot - W_dobrom budúcnosť (ŽP07)'),
//            (150,   3,  1,  'WUS_POHODA',   'Wustenrot - W_pohode (ŽP07)'),
//            (151,   4,  2,  'ALL_SENIOR',   'Allianz - Senior'),
//            (152,   29, 2,  'KOO_DUKATI',   'Kooperativa - Dukátik'),
//            (153,   29, 2,  'KOO_KAPITA',   'Kooperativa - Variant Kapitál SD1'),
//            (154,   6,  2,  'UNQ_UNIQAC',   'UNIQA - UNIQAČIK detské KŽP'),
//            (155,   1,  3,  'YOU_ZIVOT',    'Youplus - Životné poistenie 4U'),
//            (156,   7,  4,  'COL_ZOZ',  'Colonnade - zodpovednosť za škodu pri výkone povolania'),
//            (157,   7,  6,  'COL_PPV',  'Colonnade - poi. prepravy vecí (medzinarocnej i vnutrostatnej)'),
//            (158,   7,  8,  'COL_EUG',  'Colonnade - EuroGAP'),
//            (159,   7,  8,  'COL_TRG',  'Colonnade - TruckGAP'),
//            (160,   7,  8,  'COL_LEG',  'Colonnade - LeaseGAP'),
//            (161,   7,  4,  'COL_SMP',  'Colonnade - stavebné a montážne poistenie'),
//            (162,   31, 10, 'ATR_LOK',  'Atradius - poistenie pohladávok lokálne'),
//            (163,   31, 10, 'ATR_GLOB', 'Atradius - poistenie pohladávok globálne'),
//            (164,   10, 10, 'UNI_DUP',  'UNION - Dlhodobé úrazové poistenie'),
//            (165,   10, 10, 'UNI_DKH',  'UNION - Poistenie dennej kompenzácie za hospitalizáciu'),
//            (166,   10, 9,  'UNI_ZDR_PTE',  'UNION - Zdravotné pripoistenie Zdravie Plus PREMIUM, TOP, EXCELENT'),
//            (167,   10, 10, 'UNI_UZPN', 'UNION - Poistenie ušlého zárobku pri PN'),
//            (168,   10, 10, 'UNI_HUP',  'UNION - Hromadné úrazové poistenie osôb v MV'),
//            (169,   10, 4,  'UNI_ZOZ_INE',  'UNION - Poi. ZOZ z vlastníctva nehnut., chyba výrobku, dopravca, ...'),
//            (170,   10, 4,  'UNI_VZD',  'UNION - Poistenie všeobec. zodpovednosti dopravcov'),
//            (171,   10, 10, 'UNI_PZVV', 'UNION - Poistenie prepravy zásielok, poistenie výstav a veľtrhov'),
//            (172,   10, 10, 'UNI_CDT',  'UNION - Poistenie colného dlhu a spoločného tranzitu'),
//            (173,   10, 10, 'UNI_GAR',  'UNION - Garančné poistenie'),
//            (174,   10, 9,  'UNI_IZD',  'UNION - Individuálne zdravotné poistenie'),
//            (175,   10, 11, 'UNI_PZP_HZ',   'UNION - Povinné zmluvné poistenie HZ (flotila)'),
//            (176,   10, 11, 'UNI_PMV_HZ',   'UNION - Poistenie motorových vozidiel HZ'),
//            (177,   6,  3,  'UNQ_ACT_LIFE', 'UNIQA - ActiveLife'),
//            (178,   3,  11, 'WUS_PZP_FLO',  'Wustenrot - Flotilové PZP MV'),
//            (179,   3,  8,  'WUS_HAV',  'Wustenrot -  Poistenie MV čiastočné KASKO'),
//            (180,   3,  8,  'WUS_HAV',  'Wustenrot -  Flotilové KASKO'),
//            (181,   3,  8,  'WUS_HAV',  'Wustenrot -  Flotilové čiastočné KASKO'),
//            (182,   3,  10, 'WUS_PCS',  'Wustenrot - Poistenie čelného skla MV'),
//            (183,   3,  7,  'WUS_IZS',  'Wustenrot - Individuálne poi. nehnuteľ., domácnosti a zodp. za škodu'),
//            (184,   3,  5,  'WUS_IBD',  'Wustenrot - Individuálne poistenie bytového domu'),
//            (185,   3,  6,  'WUS_IMZ',  'Wustenrot - Individuálne poi. majetku a zodpovednosti PO'),
//            (186,   3,  8,  'WUS_GAP',  'Wustenrot - Poistenie finančnej straty SuperGAP'),
//            (187,   28, 10, 'KOM_URZ',  'Komunálna - Produkt č. 4801 K-škole'),
//            (188,   28, 1,  'KOM_INV',  'Komunálna - Provital Invest'),
//            (189,   24, 24, 'PSS_SPD_TU3',  'PSS - Stavebné sporenie môj DOMOV, tarif U3'),
//            (190,   24, 24, 'PSS_SPL_TIT',  'PSS - Stavebné sporenie Lišiak tarifa IT'),
//            (191,   23, 14, 'FIN_INJ',  'Finax - investície jednorázové'),
//            (192,   9,  26, 'UNI_DDS',  'UNIQA DDS'),
//            (193,   8,  27, 'UNI_DSS',  'UNIQA DSS'),
//            (194,   32, 15, 'UNI_TEM',  'UNIQA - Tempo'),
//            (195,   32, 15, 'UNI_PF',   'UNIQA - Podieľové fondy'),
//            (196,   6,  5,  'UNQ_FAO',  'UNIQA - Firma & Ochrana'),
//            (197,   6,  10, 'UNQ_PPS',  'UNIQA - Poistenie poľnohospodárskych strojov'),
//            (198,   6,  10, 'UNQ_URJ',  'UNIQA - Jednorázové poistenie úrazu'),
//            (199,   23, 15, 'FIN_SPOR', 'Finax - investície sporiace'),
//            (200,   21, 14, 'EIC_INJ',  'EIC - investície jednorázové'),
//            (201,   11, 15, 'COQ_3DI_TRV',  'CONSEQ - 3D Invest / Active Invest (Trvalý pokyn - bežný)'),
//            (202,   21, 15, 'EIC_SPOR', 'EIC - investície sporiace'),
//            (203,   26, 6,  'PRE_DO',   'Premium - D&O'),
//            (204,   26, 4,  'PRE_ENV',  'Premium - Environmentálne poistenie'),
//            (205,   14, 20, 'UCB_HYPO', 'UCB -  Hypotéka Presto Business'),
//            (206,   25, 10, 'GEN_UPS',  'Generali - Úrazové poistenie školák'),
//            (207,   25, 10, 'GEN_SUP',  'Generali - Skupinové úrazové poistenie'),
////            (208,   25, 11, 'GEN_PZP',  'Genertel - PZP'),
//            (209,   25, 12, 'GEN_ZHO',  'Generali - Poistenie záchrany v horách SR'),
////            (210,   25, 8,  'GEN_KASKO',    'Genertel - KASKO'),
//            (211,   25, 12, 'ECP_CP_KR',    'ECP - cestovné poistenie krátkodobé'),
//            (212,   25, 12, 'ECP_RCP',  'ECP - cestovné poistenie ročné'),
//            (213,   11, 14, 'COQ_3DI_JED',  'CONSEQ - 3D Invest / Active Invest (Jednorazový pokyn)'),
//            (214,   11, 15, 'COQ_3DA_TPE',  'CONSEQ - 3D Invest / Active Invest (Trvalý pokyn - expresný)'),
//            (215,   11, 14, 'COQ_CLI',  'CONSEQ - Classic Invest (Jednorazová investícia)'),
//            (216,   11, 15, 'COQ_3DI_TRV',  'CONSEQ - Classic Invest (Trvalý pokyn - bežný)'),
//            (217,   11, 15, 'COQ_CLI',  'CONSEQ - Classic Invest (Trvalý pokyn - expresný)'),
//            (218,   34, 12, 'AXA_AS_ICP',   'AXA ASSISTANCE - individuálne cestovné poistenie'),
//            (219,   34, 12, 'AXA_ASS_CPSK', 'AXA ASSISTANCE - cestovné poistenie pre SK'),
//            (220,   35, 27, 'VUBG_SDS', 'VÚB Generali'),
//            (221,   27, 15, 'IAD_FND',  'IAD - Fondy'),
//            (222,   27, 15, 'IAD_SPR',  'IAD - Sporenie'),
//            (223,   27, 15, 'IAD-ETF',  'IAD - ETF Sporenie'),
//            (224,   23, 14, 'FIN_PR_INJ',   'Finax prevod - investície jednorázové'),
//            (225,   23, 15, 'FIN_PR_SPOR',  'Finax prevod - investície sporiace'),
//            (226,   29, 10, 'KOOP_CS',  'Kooperativa - Čelné sklo'),
//            (227,   25, 1,  'GEN_LAV_IZP',  'Generali - La Vita IŽP'),
//            (228,   25, 11, 'GEN_FLOT', 'Generali - Flotila'),
//            (229,   3,  4,  'WUS_ZOZ',  'Wustenrot - Poistenie zodpovednosti za škodu výkonom advokácie'),
//            (230,   10, 12, 'UNI_CP_HZS',   'UNION - cestovné poistenie HZS'),
//            (231,   13, 6,  'ČSOB_PPBP',    'ČSOB  - poistenie podnikateľov BIZNIS Plus'),
//            (232,   10, 12, 'UNI_HCP',  'UNION - hromadné cestovné zmluvy'),
//            (233,   36, 10, 'DEF_GAP',  'DEFEND GAP'),
//            (234,   36, 10, 'DEF_CAR_PRT',  'DEFEND Car Protect'),
//            (235,   36, 10, 'DEF_TEC',  'DEFEND Technical Control'),
//            (236,   36, 10, 'DEF_KYP',  'DEFEND Key Protect'),
//            (237,   18, 20, 'TB_KK_POD',    'TATRA BANKA - Kreditné karty (pre podnikateľov)'),
//            (238,   15, 21, 'ČSOB_LEAS_SPU',    'ČSOB - Leasing (spotrebiteľský úver)'),
//            (239,   37, 1,  'NN_PLN',   'NN Plan'),
//            (240,   40, 18, 'BKS_NOMV', 'BKS LEASING - nových a ojazdených MV'),
//            (241,   12, 21, 'ČSOB_spotreb', 'ČSOB Banka - Spotrebiteľský úver'),
//            (242,   12, 21, 'ČSOB_spot_ref',    'ČSOB Banka - Spotrebiteľský úver refinančný'),
//            (243,   34, 12, 'AXA_for_Bus',  'AXA ASSISTANCE - Travel 4 Business'),
//            (244,   34, 12, 'AXA_CUDZ', 'AXA ASSISTANCE - poistenie pre cudzincov'),
//            (245,   40, 18, 'BKS_TECH', 'BKS LEASING - technológie'),
//            (246,   29, 1,  'KOOP_BUDUC',   'Kooperativa - moja budúcnosť'),
//            (247,   10, 10, 'UNI_URZ',  'UNION - Úrazové poistenie'),
//            (248,   25, 12, 'ECP_PSC',  'ECP - poistenie služobných ciest'),
//            (249,   29, 10, 'KOOP_EM',  'Kooperativa - Enviro max'),
//            (250,   13, 5,  'ČSOB_PRM', 'ČSOB  - poistenie podnikateľských rizík a majetku'),
//            (251,   13, 6,  'ČSOB_BDBP',    'ČSOB - Bytové domy v produkte BIZNIS Plus'),
//            (252,   18, 20, 'TB_PU_BB', 'TATRA BANKA - Podnikateľské úvery (BIUEX, BIUVARIANT)'),
//            (253,   18, 23, 'TB_POST',  'TATRA BANKA - POS terminál, CARD PAY'),
//            (254,   18, 25, 'TB_PU',    'TATRA BANKA - Podnikateľské účty'),
//            (255,   18, 21, 'TB_KK_FO', 'TATRA BANKA - Kreditné karty (pre FO)'),
//            (256,   12, 23, 'ČSOB_WP',  'ČSOB Banka - WebPay');");
    }
}
